language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"
env: TOXENV=py

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=tz
    - python: 3.7
      env: TOXENV=build
  allow_failures:
    - python: "nightly"

install:
  - pip install -U "tox<3.8.0" $PIP_ARGS
  - if [[ $TOXENV == "py" ]]; then ./ci_tools/retry.sh python updatezinfo.py; fi

script:
  - tox
  - |
    if [[ $TOXENV == "build" ]]; then
      exactly_one() {
        value=$(find dist -iname $1 | wc -l)
        if [ $value -ne 1 ]; then
          echo "Found $value instances of $1, not 1"
          return 1
        else
          echo "Found exactly 1 instance of $value"
        fi
      }

      # Check that exactly one tarball and one wheel are created
      exactly_one '*.tar.gz'
      exactly_one '*.whl'
    fi

after_success:
  - if [[ $TOXENV == "py" ]]; then tox -e coverage,codecov; fi
